param(
    [string]$Root = (Split-Path -Parent $PSScriptRoot),
    [string]$AssemblyPath = (Join-Path $PSScriptRoot '..\tmp\political-border-editor\bin\Win64_Shipping_Client\AgesOfCalradia.PoliticalBorderEditor.dll')
)

$ErrorActionPreference = 'Stop'
$project = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderEditor.csproj') -Raw
$state = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderEditorState.cs') -Raw
$document = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderEditorDocument.cs') -Raw
$subModule = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderEditorSubModule.cs') -Raw
$manifest = Get-Content -LiteralPath (Join-Path $Root 'SubModule.xml') -Raw
$optimizer = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderAuthoredOverrides.cs') -Raw
$ui = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderEditorUi.cs') -Raw
$grid = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderEditorGrid.cs') -Raw
$overlay = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderReferenceOverlay.cs') -Raw
$terrainSnapshot = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderTerrainSnapshot.cs') -Raw
$preview = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderEditorPreview.cs') -Raw
$scenePreview = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderEditorScenePreview.cs') -Raw
$topDownCamera = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderEditorTopDownCamera.cs') -Raw
$sounds = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderEditorSounds.cs') -Raw
$prefab = Get-Content -LiteralPath (Join-Path $Root 'GUI\Prefabs\PoliticalBorderEditor.xml') -Raw

function Assert-True([bool]$Condition, [string]$Message) {
    if (-not $Condition) { throw $Message }
}

Assert-True ($project -match '<AssemblyName>AgesOfCalradia\.PoliticalBorderEditor</AssemblyName>' -and $project -match 'PoliticalBorderEditorDocument\.cs' -and $project -match 'PoliticalBorderReferenceOverlay\.cs' -and $project -match 'PoliticalBorderEditorPreview\.cs' -and $project -match 'PoliticalBorderEditorScenePreview\.cs' -and $project -match 'PoliticalBorderEditorTopDownCamera\.cs' -and $project -match 'PoliticalBorderEditorPathMath\.cs' -and $project -match 'PoliticalBorderEditorSounds\.cs' -and $project -notmatch '<AssemblyName>AgesOfCalradia</AssemblyName>') 'The editor is not isolated in its own focused sidecar assembly.'
Assert-True ($manifest -match 'AgesOfCalradia\.PoliticalBorderEditor\.dll' -and $manifest -match 'PoliticalBorderEditorSubModule') 'The editor sidecar is not registered in the module manifest.'
Assert-True ($subModule -match 'SandBox\.View\.Map\.MapScreen' -and $subModule -match 'HandleLeftMouseButtonClick' -and $subModule -match 'OnFrameTick' -and $subModule -match 'Native targets:' -and $subModule -match 'Compatibility risk:' -and $subModule -match 'Failure behavior:' -and $subModule -match 'Verification:') 'The native map input patch contract is incomplete.'
Assert-True ($subModule -match 'UnpatchAll\(HarmonyId\)' -and $subModule -match 'normal map input remains active') 'Version-sensitive editor binding does not fail closed.'
Assert-True ($state -match 'InputKey\.F10' -and $state -match 'InputKey\.L' -and $state -match 'InputKey\.K' -and $state -match 'InputKey\.G' -and $state -match 'InputKey\.H' -and $state -match 'InputKey\.J' -and $state -match 'InputKey\.R' -and $state -match 'InputKey\.N') 'Line, curve, coast-follow, reference-trace, freeform, camera, smooth, or editor-toggle controls are missing.'
Assert-True ($state -match 'BorderTool\.Reference' -and $state -match 'TryBuildRoute' -and $state -match 'SmoothActiveBorder') 'The road-style reference trace or smoothing behavior is incomplete.'
Assert-True ($state -match 'PageUp' -and $state -match 'PageDown' -and $state -match 'ResizeBrush' -and $state -match 'FillBrush') 'The political fill brush or adjustable radius controls are incomplete.'
Assert-True ($state -match 'start on an existing yellow node' -and $state -match 'must close on its first yellow node' -and $state -match 'TrySnapToBorderNetwork') 'Open authored borders can be saved as disconnected paths.'
Assert-True ($state -match 'canCloseAtStart' -and $state -match 'ConnectionSnapDistance \* 2f' -and $state -notmatch 'foreach \(Vec2 candidate in ActivePoints\)') 'Freeform samples can snap to the preceding active point and commit prematurely.'
Assert-True ($state -match 'InferFaction\(Vec2 point\)' -and $state -match 'Settlement\.All' -and $state -match 'settlement\.IsTown' -and $state -match 'settlement\.IsCastle' -and $state -match 'settlement\.IsVillage' -and $state -match 'settlement\.OwnerClan' -and $state -match 'kingdom:' -and $state -match 'clan:') 'Faction inference does not match the political renderer nearest-owned-settlement site contract.'
Assert-True ($state -match 'if \(ActivePoints\.Count == 0 && !TryLockFaction\(point\)\) return;' -and $state -match 'FactionId = faction\.Id' -and $state -match 'AuthoredBorderColor = 0xFF000000u' -and $state -match 'Color = AuthoredBorderColor' -and $state -match 'FactionId = path\.FactionId' -and $state -match 'Color = faction\.Color') 'Black authored borders and their automatically inferred faction fill do not share the same ownership assignment.'
Assert-True ($state -match 'PlanningBorderColor = 0xFF181818u' -and ([regex]::Matches($state, 'RenderDottedPath\([\s\S]{0,180}PlanningBorderColor\)')).Count -ge 4 -and $state -match 'RenderAnchor\([\s\S]{0,100}PlanningBorderColor\)') 'Every staged line, anchor, route, and confirmed plan is not using the visible shader-safe planning color.'
Assert-True ($state -match 'CursorPreviewColor = PlanningBorderColor' -and $state -match 'CoastRoutePreviewColor = PlanningBorderColor') 'Crosshair, coast route, and dotted planning lines do not share the same visible black presentation.'
Assert-True ($state -notmatch 'InputKey\.C|CycleFaction|RefreshFactions|UiCycleFaction' -and $ui -notmatch 'ExecutePreviousFaction|ExecuteNextFaction' -and $prefab -notmatch 'ExecutePreviousFaction|ExecuteNextFaction' -and $prefab -match 'AUTO-DETECTED FACTION') 'Manual faction selection remains exposed in the automatic editor workflow.'
Assert-True ($state -match 'NeutralFillColor = 0xFFA8A096u' -and $state -match 'FactionId = path\.FactionId' -and $state -match 'Color = faction\.Color' -and $prefab -match 'Command\.Click="ExecuteFillBrush"') 'Authored fill does not retain its inferred faction color while the temporary white presentation is active.'
Assert-True ($document -match 'MaximumFileBytes' -and $document -match 'MaximumPointsPerShape' -and $document -match 'File\.Replace' -and $document -match 'FillBrush' -and $document -match 'borderWidthScale' -and $document -match 'NormalizeStyle') 'The human-readable override document is not bounded, atomic, width-aware, style-aware, or brush-aware.'
Assert-True ($optimizer -match 'ValidateBorderConnectivity' -and $optimizer -match 'connected chains with shared endpoints' -and $optimizer -match 'only recolors triangles') 'The runtime does not enforce connected borders and exclusion-safe fill edits.'
Assert-True ($ui -match 'GlobalLayer' -and $ui -match 'GauntletLayer' -and $ui -match 'keyboard controls remain active' -and $prefab -match 'TownManagement\.GovernorPopup\.GoldFrame' -and $prefab -match 'ExecuteFollowCoast' -and $prefab -match 'ExecuteFillBrush') 'The Refuge Builder-style interactive editor panel or its keyboard fallback is incomplete.'
foreach ($command in @(
    'ExecuteLine', 'ExecuteCurve', 'ExecuteFollowCoast', 'ExecuteReference', 'ExecuteFreeform', 'ExecuteSculpt', 'ExecuteGenerated', 'ExecutePartyTrace',
    'ExecuteSmooth', 'ExecuteFillBrush', 'ExecuteSmallerBrush', 'ExecuteLargerBrush',
    'ExecuteUndo', 'ExecuteDelete', 'ExecuteReady', 'ExecuteCommit', 'ExecuteSave',
    'ExecuteToggleGrid', 'ExecuteToggleReference', 'ExecuteToggleCamera',
    'ExecuteCycleSettlementVisibility', 'ExecuteToggleCloseZoomFill',
    'ExecuteThinnerBorders', 'ExecuteThickerBorders', 'ExecuteCycleBorderStyle',
    'ExecuteClose')) {
    Assert-True ($ui -match "public void $command" -and $prefab -match "Command\.Click=`"$command`"") "Editor button is not functionally wired: $command"
}
Assert-True (([regex]::Matches($ui, 'public void Execute\w+\(\) \{ ExecuteCommand\(')).Count -eq 26 -and $ui -match 'Editor UI command invoked:' -and $ui -match 'Editor UI command completed:' -and $ui -match 'Editor UI command failed:') 'Not every editor button is routed through invoked/completed/failed command diagnostics.'
Assert-True ($ui -match 'Layer\.IsFocusLayer = true' -and $ui -match 'ScreenManager\.TrySetFocus' -and $ui -match 'SetInputRestrictions\(\s*true, InputUsageMask\.MouseButtons\)' -and $state -match 'IsPointerOverPanel' -and $state -match 'pointerOverPanel') 'The interactive panel is not registered for mouse-button hit routing or does not exclude panel clicks from drawing.'
Assert-True ($prefab -match '<Window>\s*<Widget WidthSizePolicy="Fixed" HeightSizePolicy="Fixed" SuggestedWidth="520" SuggestedHeight="900"' -and $prefab -notmatch '<Window>\s*<Widget DoNotAcceptEvents="true" WidthSizePolicy="StretchToParent"' -and $ui -match 'Editor UI pointer release: layerHit=') 'The map-global movie still has an illegible or non-interactive root instead of a readable panel-sized hit-test root.'
Assert-True ($grid -match 'CellSideMiles = 10f' -and $grid -match 'CellAreaSquareMiles = 100f' -and $grid -match 'MaximumRenderedSegments' -and $state -match 'UiToggleGrid' -and $prefab -match 'ExecuteToggleGrid') 'The bounded toggleable 100-square-mile planning grid is incomplete.'
Assert-True ($grid -match 'GridLift = 0\.05f' -and $grid -match 'GridColor = 0xAA165A32u' -and $overlay -match 'OverlayLift = 0\.10f') 'The planning grid is not terrain-locked, dark green, and below the red reference overlay.'
Assert-True ($grid -match 'GridRenderOrder = 90' -and $overlay -match 'OverlayRenderOrder = 91' -and $scenePreview -match 'RenderOrder = 120' -and $scenePreview -match 'MaterialFlags\.NoDepthTest') 'Green/red guides are not ordered below the political fill while active planning marks remain above it.'
Assert-True ($scenePreview -match 'MeshBuilder' -and $scenePreview -match 'GameEntity\.CreateEmpty' -and $scenePreview -match 'MaterialFlags\.NoDepthTest' -and $scenePreview -match 'CreatePersistentEntity' -and $preview -match 'PoliticalBorderEditorScenePreview\.AddLine' -and $preview -match 'PoliticalBorderEditorScenePreview\.AddDisc') 'Crosshair and staged plans still depend on Shipping Client debug primitives instead of production scene geometry.'
Assert-True ($scenePreview -match 'Campaign\.MapSceneWrapper\.Scene' -and $scenePreview -match 'GetProperty\(wrapper, "Scene"\)' -and ([regex]::Matches($scenePreview, 'SetVisibilityExcludeParents\(true\)')).Count -eq 2 -and ([regex]::Matches($scenePreview, 'SetEnforcedMaximumLodLevel\(0\)')).Count -eq 2 -and ([regex]::Matches($scenePreview, 'UpdateVisibilityMask\(\)')).Count -eq 2) 'Dynamic or persistent editor geometry is not attached to the campaign-map scene and explicitly made visible like the working political renderer.'
Assert-True ($grid -match 'CreatePersistentEntity' -and $grid -match 'rendered < MaximumRenderedSegments' -and $grid -match 'SetVisible' -and $overlay -match 'CreatePersistentEntity' -and $overlay -match '_nextTerrainNode < Nodes\.Count' -and $state -match 'PoliticalBorderEditorGrid\.SetVisible') 'Grid or reference overlays are not persistent bounded production meshes with functional visibility toggles.'
Assert-True ($topDownCamera -match 'MatrixFrame\.CreateLookAt' -and $topDownCamera -notmatch 'MaximumCameraHeight' -and $topDownCamera -match 'CameraDistance' -and $topDownCamera -match 'TargetCameraDistance' -and $topDownCamera -match 'CameraBearing' -and $topDownCamera -match 'current native zoom' -and $topDownCamera -match 'internal static void Restore' -and $state -match '_cameraNavigation = false;' -and $state -match 'CAMERA: 2D EDITING' -and $state -match 'PoliticalBorderEditorTopDownCamera\.Apply\(mapScreen\)' -and $state -match 'PoliticalBorderEditorTopDownCamera\.Restore\(\)') 'F10 does not default to and reversibly restore the north-up 2D camera at the current native zoom.'
Assert-True ($overlay -match 'ExpectedWidth = 1672' -and $overlay -match 'CellPixels = 6' -and $overlay -match 'MaximumSegments = 12000' -and $overlay -match 'RegisteredLeft = 411f' -and $overlay -match 'RegisteredWidth = 702f' -and $overlay -match 'TryGetCampaignToReferenceProjection' -and $overlay -match 'Unproject' -and $overlay -match 'TerrainSamplesPerFrame = 160' -and $overlay -match 'TryBuildRoute') 'The PNG guide is not projected through the calibrated terrain transform or exposed as a bounded connected TRACE graph.'
Assert-True ($terrainSnapshot -match 'Width = 1041' -and $terrainSnapshot -match 'Height = 1041' -and $terrainSnapshot -match 'WorldMinimum = 0f' -and $terrainSnapshot -match 'WorldMaximum = 1040f' -and $terrainSnapshot -match 'CoordinateMode = "bannerlord-world-v1"' -and $terrainSnapshot -match 'SceneToken' -and $terrainSnapshot -match 'SamplesPerFrame = 256' -and $terrainSnapshot -match 'GetHeightAtPoint' -and $terrainSnapshot -match 'GetTerrainTypeAtPosition' -and $terrainSnapshot -notmatch 'Unproject|MapPixelWidth|CropLeft' -and $terrainSnapshot -match 'File.Replace' -and $state -match 'PoliticalBorderTerrainSnapshot.Tick' -and $state -match 'PoliticalBorderTerrainSnapshot.Begin') 'The high-detail external editor terrain snapshot is not exact-world, classified, bounded, incremental, atomic, or connected to F10 planning.'
Assert-True ($overlay -match 'hasOrthogonalContinuation' -and $overlay -match 'HasSourceLineSupport' -and $overlay -match '!hasOrthogonalContinuation && followsSourceLine' -and $overlay -match 'if \(!edge\.Render\) continue;' -and $overlay -match 'OverlayColor = 0xFF650B12u' -and $overlay -match 'OverlayColor, 0\.38f') 'The visible red guide still renders unsupported routing chords or diagonals as a pale triangular net.'
Assert-True ($state -match '_cameraNavigation' -and $state -match 'return false;' -and $ui -match 'SetCameraNavigation' -and $ui -match 'Editor UI focus retained for camera mode' -and $ui -match 'TrySetFocus' -and $ui -notmatch 'if \(navigation\)\s*\{\s*_active\.Layer\.IsFocusLayer = false') 'Camera navigation can strand the toolbar without focus or cannot safely suspend drawing.'
Assert-True ($state -match 'UiResizeAllBorders' -and $document -match 'BorderWidthScale = 1f' -and $prefab -match 'THINNER' -and $prefab -match 'THICKER') 'The global all-border width control is incomplete.'
Assert-True ($state -match 'return "TOOL: "' -and $state -match 'return "WIDTH "' -and $prefab -match 'Text="@Tool"' -and $prefab -match 'Text="@BorderWidth"' -and $prefab -notmatch 'TOOL: @Tool|WIDTH @BorderWidth') 'Gauntlet dynamic tool or width labels still rely on unsupported inline binding interpolation.'
Assert-True ($state -match 'CycleBorderStyle' -and $document -match 'Style = "Solid"' -and $preview -match '"Dashed"' -and $preview -match '"Double"') 'Solid, dashed, and double authored-border varieties are not persisted and previewed.'
Assert-True ($state -match 'PoliticalBorderEditorSounds\.PlayBorderPlaced\(\)' -and $sounds -match 'SoundEvent\.PlaySound2D' -and $sounds -match 'editor audio was disabled while drawing remains active') 'Committed border placement does not have a fail-safe confirmation sound.'
Assert-True ($subModule -match 'SettlementNameplateVM' -and $subModule -match 'UpdateNameplateMT' -and $subModule -match 'Priority\.Last' -and $subModule -match '____bindIsVisibleOnMap' -and $subModule -match '____isTown' -and $subModule -match '____isCastle' -and $subModule -match '____isVillage' -and $state -match 'if \(!_active\) return;' -and $state -match 'SettlementVisibilityMode\.All' -and $state -match 'SettlementVisibilityMode\.TownsAndCastles' -and $state -match 'SettlementVisibilityMode\.TownsOnly' -and $prefab -match 'ExecuteCycleSettlementVisibility') 'The editor-only town/castle/village visibility cycle is incomplete or can leak outside editor mode.'
Assert-True ($optimizer -match 'SuppressGeneratedCoasts = true' -and $state -match 'PoliticalBorderGeneratedOverlay\.StatusText') 'Generated coastal ribbons are not suppressed while their editable centerline plans remain available.'
Assert-True ($state -match 'CursorPreviewColor' -and $state -match 'CoastRoutePreviewColor' -and $state -match 'RenderCursorPreview' -and $preview -match 'RenderTerrainRing' -and $preview -match 'RenderCrosshair' -and $preview -match 'RenderDottedPath') 'Placed-border, ghost-route, cursor, or fill-brush visual previews are incomplete.'
Assert-True ($state -match 'ActivePointerCrosshairRadius = 6f' -and $state -match 'pointerActive = Input\.IsKeyDown\(InputKey\.LeftMouseButton\)' -and $state -match 'crosshairThickness = pointerActive \? 10 : 6') 'Map clicks and drags do not receive a full-map-visible active crosshair across editor tools.'
Assert-True ($state -match '_hasCursorPreview = TryGetCursorMapPoint' -and $state -notmatch '_hasCursorPreview = !pointerOverPanel' -and $state -match 'pointerOverPanel\s*&&' -and $state -match '!pointerOverPanel') 'The F10 panel suppresses the visual crosshair or panel hits are no longer excluded from placement.'
Assert-True ($ui -match 'SetInputRestrictions\(\s*true, InputUsageMask\.MouseButtons\)' -and $ui -notmatch 'SetInputRestrictions\(\s*false, \(InputUsageMask\)0\)' -and $state -match 'FindInstanceField' -and $state -match 'FindInstanceMethod' -and $state -match 'BindingFlags\.DeclaredOnly') 'The panel does not consume button clicks while preserving keyboard/wheel map input, or NavalMapScreen cursor projection cannot walk inherited private members.'
Assert-True ($state -match 'TryCreateLiveCursorRay' -and $state -match 'FindInstanceProperty' -and $state -match 'MapCameraView' -and $state -match 'ScreenSpaceRayProjection' -and $state -match 'Input\.MousePositionRanged') 'The crosshair depends only on MapScreen mouse handling and cannot follow the live cursor while the Gauntlet panel has focus.'
Assert-True ($state -match 'Ray ray = \(Ray\)_mouseRayField\.GetValue' -and $state -match 'IsUsableMapIntersection' -and $state -match 'TryProjectRayToMapPlane' -and $state -match 'Math\.Abs\(point\.x\) \+ Math\.Abs\(point\.y\) > 1f') 'Cursor projection still accepts Bannerlord''s invalid zero output or lacks a maintained-ray plane fallback.'
Assert-True ($preview -match 'PreviewLift = 0\.15f' -and $state -match 'Editor cursor release: projected=' -and $state -match 'screen=' -and $state -match 'panelHit=') 'The active crosshair is not terrain-locked just above both persistent guides or lacks click-time projection diagnostics.'
Assert-True ($state -match 'Native map click produced an invalid coordinate; using the projected cursor fallback' -and $state -match 'if \(!IsUsableMapPoint\(point\)\)' -and $state -match 'Border point accepted: count=') 'Invalid native zero clicks can still suppress the valid maintained-ray fallback, or line-anchor diagnostics are missing.'
Assert-True ($subModule -match 'SetPoliticalOverlayAlpha' -and $subModule -match 'BeforePoliticalOverlayAlpha' -and $state -match 'EditorPoliticalFillOpacity = 0\.18f' -and $state -match 'ApplyCloseZoomFill' -and $state -match 'alpha \* EditorPoliticalFillOpacity' -and $state -match 'POLITICAL FILL: VISIBLE ALL ZOOMS' -and $state -match 'POLITICAL FILL: HIDDEN' -and $prefab -match 'ExecuteToggleCloseZoomFill') 'F10 planning does not provide all-zoom, overview-only, and hidden political-fill states.'
Assert-True ($state -match 'BorderTool\.Sculpt' -and $state -match 'UpdateSculptDrag' -and $state -match 'CollectSculptTargets' -and $state -match 'FillPolygon polygon' -and $state -match 'SCULPT change staged' -and $prefab -match 'ExecuteSculpt') 'Committed border nodes and their matching fill points cannot be click-drag sculpted as a connected staged plan.'
Assert-True ($state -match 'BorderTool\.Generated' -and $state -match 'UpdateGeneratedEdit' -and $state -match 'ReplacesGenerated = _editingGenerated' -and $ui -match 'ExecuteGenerated' -and $prefab -match 'Command\.Click="ExecuteGenerated"') 'Generated borders cannot be promoted into editable staged plans from the UI.'
Assert-True ($state -match 'Generated anchor drag started:' -and $state -match 'Generated anchor drag completed:' -and $state -match 'ActivePoints\[_generatedDragIndex\] = _cursorPreviewPoint') 'Generated circle-and-dot anchors cannot be click-dragged with decisive diagnostics.'
Assert-True ($state -match 'TryInsertGeneratedAnchor' -and $state -match 'Generated segment manipulation started:' -and $state -match 'ActivePoints\.Insert\(insertedIndex, closest\)' -and $state -match 'MaximumPointsPerShape') 'Generated lines cannot be directly click-dragged to insert a bounded control point and bend the staged path.'
Assert-True ($document -match 'replacesGenerated' -and $optimizer -match 'replacementEdges' -and $optimizer -match 'ReplacesGenerated') 'Generated-chain replacement is not persisted backward-compatibly or applied selectively.'
Assert-True ($state -match 'Math\.Max\(0\.10f' -and $ui -match 'UiResizeBrush\(-0\.25f\)' -and $ui -match 'UiResizeBrush\(0\.25f\)' -and $state -match 'ToString\("F2"') 'The fill brush lacks precise quarter-step controls and a fine minimum radius.'
Assert-True ($state -match 'BorderTool\.PartyTrace' -and $state -match 'MobileParty\.MainParty' -and $state -match 'UpdatePartySurvey' -and $state -match 'ArmyPositionAdder' -and $state -match '<ArmyPositionAdder>k__BackingField' -and $state -notmatch 'party\.Position\s*=' -and $state -match 'PartySurveySpeed = 12f' -and $state -match 'FastPartySurveySpeed = 30f' -and $state -match 'InputKey\.W' -and $state -match 'InputKey\.A' -and $state -match 'InputKey\.S' -and $state -match 'InputKey\.D' -and $state -match '>= 0\.25f' -and $state -match 'RestorePartySurveyVisual' -and $ui -match 'HideForPartyTrace' -and $prefab -match 'Text="SURVEY"') 'Paused mountain-survey movement cannot record a bounded black border plan or safely restore the party visual offset without changing its logical position.'
Assert-True ($state -match 'CampaignTimeControlMode\.Stop' -and $state -notmatch 'CampaignTimeControlMode\.StoppablePlay' -and $state -match '_timeModeBeforeEditor' -and $state -match 'could not restore the prior campaign time mode') 'Planning or mountain surveying does not keep campaign AI frozen and restore the prior time mode.'
Assert-True ($state -match 'InputKey\.Tab' -and $state -match 'PLANNING MODE READY' -and $ui -match 'HideForDrawing' -and $prefab -match 'ExecuteReady') 'READY planning mode cannot hide and restore the panel while drawing remains active.'
Assert-True ($state -match 'tool == BorderTool\.Reference' -and $state -match 'PoliticalBorderReferenceOverlay\.SetVisible\(true\)' -and $overlay -match 'SetVisible\(bool visible\)') 'TRACE does not automatically expose the calibrated red planning overlay.'
Assert-True ($preview -match 'RenderDottedPath' -and $preview -match 'points\.Count == 1' -and $preview -match 'RenderAnchor\(points\[0\], color\)' -and $preview -match 'AnchorRingRadius = 0\.72f' -and $preview -match 'AnchorDotRadius = 0\.18f' -and $preview -match 'PlanningDashLength = 0\.95f' -and $preview -match 'PlanningDashGap = 0\.70f' -and $preview -match 'PlanningDashThickness = 8' -and $preview -match 'RenderLineSegment' -and $state -match 'path\.Points, path\.Closed, PlanningBorderColor' -and $state -match 'ActivePoints, false, PlanningBorderColor' -and $state -match 'RenderAnchor' -and $state -match 'referenceRoute, false, PlanningBorderColor' -and $state -match 'preview, false, PlanningBorderColor') 'Committed, circular anchors, active, projected, or PARTY TRACE planning borders are not consistently rendered as full-map-visible near-black dotted geometry.'
Assert-True ($scenePreview -match '_retiredEntity' -and $scenePreview -match 'RemoveEntity\(ref _retiredEntity\)' -and $scenePreview -match '_retiredEntity = _entity' -and $scenePreview -match 'Live border/anchor geometry published above the cursor baseline') 'Dynamic plan geometry is still removed before Bannerlord can present it for a complete render frame or lacks decisive publication diagnostics.'
Assert-True ($state -match 'RequestPoliticalRebuild' -and $state -match '_dirty' -and $state -match '_lastOwnershipSignature') 'Saving does not request a political renderer rebuild.'
Assert-True ($project -notmatch 'WorldCalendar\.xml|AgesOfCalradia\.dll') 'The editor project references a protected artifact.'
Assert-True (Test-Path -LiteralPath $AssemblyPath -PathType Leaf) 'The editor Release assembly is missing.'

Write-Host 'Political border editor verification passed: connected line/curve/freeform borders, smoothing, faction ownership, and adjustable fill brush are present.'
