param(
    [string]$Root = (Split-Path -Parent $PSScriptRoot),
    [string]$AssemblyPath = (Join-Path $PSScriptRoot '..\tmp\political-border-optimizer\bin\Win64_Shipping_Client\AgesOfCalradia.PoliticalBorderOptimizer.dll'),
    [string]$ApprovedRendererPath = 'C:\Program Files\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules\AOC CORE\bin\Win64_Shipping_Client\AgesOfCalradia.dll',
    [string]$MapScreenAssemblyPath = 'C:\Program Files\Steam\steamapps\common\Mount & Blade II Bannerlord\Modules\SandBox\bin\Win64_Shipping_Client\SandBox.View.dll'
)

$ErrorActionPreference = 'Stop'
$source = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderOptimizerSubModule.cs') -Raw
$eagerWarmupSource = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderEagerWarmup.cs') -Raw
$geometryCacheSource = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderGeometryCache.cs') -Raw
$geometryDiagnosticsSource = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderGeometryDiagnostics.cs') -Raw
$artifactDiagnosticsSource = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderArtifactDiagnostics.cs') -Raw
$geometryRepairSource = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderGeometryRepair.cs') -Raw
$publishedLayoutSource = Get-Content -LiteralPath (Join-Path $Root 'PublishedBorderLayoutPresence.cs') -Raw
$publishedProbeMemoSource = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderPublishedExactProbeMemoization.cs') -Raw
$authoredOverridesSource = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderAuthoredOverrides.cs') -Raw
$editorStateSource = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderEditorState.cs') -Raw
$coastalFillClipperSource = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderCoastalFillClipper.cs') -Raw
$coastalContourSource = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderCoastalContourSmoother.cs') -Raw
$chainBuilderSource = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderChainBuilder.cs') -Raw
$strokeTessellatorSource = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderStrokeTessellator.cs') -Raw
$ribbonDiagnosticSource = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderRibbonDiagnosticSamples.cs') -Raw
$ribbonRebuilderSource = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderRibbonRebuilder.cs') -Raw
$project = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderOptimizer.csproj') -Raw
$editorProject = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderEditor.csproj') -Raw
$documentSource = Get-Content -LiteralPath (Join-Path $Root 'PoliticalBorderEditorDocument.cs') -Raw
$manifest = Get-Content -LiteralPath (Join-Path $Root 'SubModule.xml') -Raw
$documentation = Get-Content -LiteralPath (Join-Path $Root 'docs\POLITICAL_BORDER_OPTIMIZER.md') -Raw

function Assert-True([bool]$Condition, [string]$Message) {
    if (-not $Condition) { throw $Message }
}

Assert-True ($source -match '560F1B5181F8CC2EFE51564D8675FD3089E722606FA55B0B166D36ECD9868D8E') 'The sidecar does not pin the approved renderer hash.'
Assert-True ($source -match 'CampaignMapTerrainGridCache' -and $source -match 'CampaignPoliticalTerritoryFill\+Builder' -and $source -match 'IsPoliticalLandExact') 'Required protected renderer targets are not resolved by name.'
Assert-True ($source -match 'BeginOrAdvance' -and $source -match 'TrySampleExactHeight' -and $source -match 'TryGetNativeTerrain') 'Terrain snapshot interception targets are incomplete.'
Assert-True ($source -match 'return true;' -and $source -match 'original probes remain active') 'Cached probe misses do not have a documented fail-open path.'
Assert-True ($source -match 'PreparedTopologyColumns = 384' -and $source -match 'PreparedTopologyWorkBudgetMilliseconds = 3d' -and $source -match 'AdvancePreparedTopology') 'The optimizer does not prepare a bounded high-resolution terrain snapshot.'
Assert-True ($source -match 'TryExactHeightDelegate' -and $source -match '_preparedHeightsValid' -and $source -match 'fractionX' -and $source -match 'fractionY') 'The optimizer does not preserve exact-height detail through its high-resolution vertex snapshot.'
Assert-True ($source -match 'TryResolvePreparedTerrain' -and $source -match 'hasTerrain = _preparedTerrainValid\[index\]') 'Cached invalid terrain cells are not handled as definitive results.'
Assert-True ($source -match 'preparedHeightHits=' -and $source -match 'preparedTerrainHits=' -and $source -match 'preparedTerrainInvalidHits=' -and $source -match 'maximumAdvanceMilliseconds=') 'Aggregate performance diagnostics are incomplete.'
Assert-True ($source -match 'publishedExactHeightMemoHits=' -and $source -match 'publishedExactHeightMemoMisses=' -and $source -match 'publishedNativeTerrainMemoHits=' -and $source -match 'publishedNativeTerrainMemoMisses=' -and $source -match 'publishedExactProbeCapacityFallbacks=') 'Published exact-probe performance diagnostics are incomplete.'
Assert-True ($source -match 'OnGameLoadFinished' -and $source -match 'EagerPoliticalBorderWarmup') 'The eager campaign-load warmup target is not registered.'
Assert-True ($source -match 'OnSessionLaunched' -and $source -match 'AfterSessionLaunched' -and $eagerWarmupSource -match 'LoadingGate.TryDismiss' -and $project -match 'PoliticalBorderLoadingDismissalPatch.cs' -and $source -match 'GuardLoadingDismissal' -and $source -match 'MapLoadingClosed') 'Session startup and loading dismissal integration are incomplete.'
Assert-True ($source -match 'Native faction fill colours, inland ownership borders, and faction-name labels are preserved' -and $source -notmatch 'PoliticalFactionColorOverrides') 'Native faction colours, ownership borders, or faction-name labels are still intercepted.'
Assert-True ($geometryCacheSource -notmatch 'ApplyUnifiedFillColor|recoloredFillTriangles') 'Temporary unified fill recolouring can still override native faction colours.'
Assert-True ($eagerWarmupSource -match 'MaximumBuildSteps = 10000' -and $eagerWarmupSource -match 'MaximumBuildMilliseconds = 30000d') 'The eager warmup does not have a bounded startup window.'
Assert-True ($eagerWarmupSource -match 'TryGetCampaignMapScene' -and $eagerWarmupSource -match 'RebuildBorders' -and $eagerWarmupSource -match '_dirty') 'The eager warmup lifecycle contract is incomplete.'
Assert-True ($eagerWarmupSource -match 'BindingFlags\.Instance \| BindingFlags\.Static' -and $eagerWarmupSource -match '_buildOwnershipSignature\.Invoke\(null, null\)') 'The eager warmup binder cannot resolve the approved private static ownership-signature method.'
Assert-True ($eagerWarmupSource -match 'normal frame-by-frame rendering remains active') 'The eager warmup does not document its fail-open behavior.'
Assert-True ($source -notmatch 'Task\.Run|new Thread|ThreadPool|GetTerrainHeightAndNormal|GameEntity|Mesh\.Create') 'The sidecar introduces worker-thread or native scene/mesh work.'
Assert-True ($eagerWarmupSource -notmatch 'Task\.Run|new Thread|ThreadPool') 'The eager warmup moves native scene work off the main thread.'
Assert-True ($geometryCacheSource -match 'AOCPBG60' -and $geometryCacheSource -match 'FormatVersion = 60' -and $geometryCacheSource -match 'MaximumCacheBytes') 'The persistent geometry cache is not versioned and bounded.'
Assert-True ($geometryCacheSource -match 'ComputeOverrideHash' -and $geometryCacheSource -match 'PoliticalBorderEditorDocument\.ResolvePath') 'Authored override changes do not invalidate the political geometry cache.'
Assert-True ($project -match 'Compile Include="PoliticalBorderEditorDocument\.cs"' -and $editorProject -match 'Compile Include="PoliticalBorderEditorDocument\.cs"' -and $documentSource -match 'FormatVersion = 1' -and $documentSource -match 'string\.IsNullOrWhiteSpace\(widthScale\)' -and $documentSource -match 'NormalizeStyle') 'Editor and optimizer no longer share the backward-compatible authored-border document contract.'
Assert-True ($geometryRepairSource -match 'PoliticalBorderAuthoredOverrides\.TryApply' -and $authoredOverridesSource -match 'ValidateBorderConnectivity' -and $authoredOverridesSource -match 'MaximumSegmentLength = 1\.5f') 'Connected authored border paths are not integrated before ribbon tessellation.'
Assert-True ($authoredOverridesSource -match 'SuppressGeneratedCoasts = true' -and $authoredOverridesSource -match 'generatedCoastsSuppressed=' -and $authoredOverridesSource -match 'IsCoastal\(segment\)' -and $authoredOverridesSource -match '\|\| IsNearAnyEdge') 'Generated ocean/lake borders are not unconditionally suppressed for the editor build.'
Assert-True ($authoredOverridesSource -match 'AddCoastFollowingEdges' -and $authoredOverridesSource -match 'FindNearestNode' -and $authoredOverridesSource -match 'FindRoute' -and $authoredOverridesSource -match 'disconnected coast components') 'The coast-following line picker does not route safely over the captured coastal graph.'
Assert-True ($authoredOverridesSource -match 'ApplyFillOverrides' -and $authoredOverridesSource -match 'TryGetBrushColor' -and $authoredOverridesSource -match 'only recolors triangles' -and $authoredOverridesSource -match 'exclusionFillCreated=false') 'Authored fill brushes do not preserve the protected fill/exclusion topology.'
Assert-True ($authoredOverridesSource -match 'NeutralAuthoredFillColor = 0xFFA8A096u' -and $authoredOverridesSource -match 'polygon\.Color == 0u' -and $authoredOverridesSource -match 'brush\.Color == 0u') 'Saved polygon and brush fill does not use its inferred faction color with a backward-compatible neutral fallback.'
Assert-True ($editorStateSource -match 'AuthoredBorderColor = 0xFF000000u' -and $authoredOverridesSource -match 'color, color,\s*edge\.Style') 'Authored border ribbons are not emitted black on both sides while retaining faction metadata.'
Assert-True ($geometryCacheSource -match 'GZipStream' -and $geometryCacheSource -match 'SHA256' -and $geometryCacheSource -match 'RendererHash') 'The persistent geometry cache key or binary format is incomplete.'
Assert-True ($geometryCacheSource -match 'MeshBuilder' -and $geometryCacheSource -match 'new Vec3\(0f, 0f, 1f\)' -and $geometryCacheSource -notmatch 'ComputeNormals\(') 'Cached geometry does not use explicit flat overlay normals.'
Assert-True ($geometryCacheSource -match 'FrontierMaterial = "vertex_color_mat"' -and $geometryCacheSource -match 'FillMaterial = "vertex_color_mat"' -and $geometryCacheSource -match 'FrontierMaterial, false, true' -and $geometryCacheSource -match 'frontierExcludeParents=false') 'Frontier replay can expose per-triangle blend seams or use a different visibility contract from the approved opaque baseline.'
Assert-True ($geometryCacheSource -match 'FrontierRenderOrder = 255' -and $geometryCacheSource -match 'MaterialFlags\.NoDepthTest' -and $geometryCacheSource -match 'MaterialFlags\.NoModifyDepthBuffer' -and $geometryCacheSource -match 'MaterialFlags\.DontDrawToDepthRenderTarget' -and $geometryCacheSource -match 'MaterialFlags\.RequiresForwardRendering' -and $geometryCacheSource -match 'MaterialFlags\.RenderOrderPlus_7' -and $geometryCacheSource -match 'CreateFrontierOverlayMaterial' -and $geometryCacheSource -match 'source\.CreateCopy\(\)' -and $geometryCacheSource -match 'frontierNoDepthOverlay=true') 'Frontier replay does not use an isolated late no-depth material copy to cover fill, terrain, and opaque objects.'
Assert-True ($geometryCacheSource -notmatch 'MBAlphaBlendMode\.ModulateNoWrite|frontierAlphaBlend=ModulateNoWrite') 'The rejected alpha-sorted frontier pass can still make captured zero-alpha borders invisible.'
Assert-True ($geometryCacheSource -match 'FillReplayLift = 0f' -and $geometryCacheSource -match 'FrontierReplayLift = 0f') 'The best-border zero-lift replay contract is not preserved.'
Assert-True ($geometryCacheSource -match 'PoliticalBorderGeometryRepair\.Apply' -and $geometryRepairSource -match 'inlandGeometryDisplacement=0\.0' -and $geometryRepairSource -match 'inlandFrontierCenterlinesPreserved=true') 'The protected inland-centerline repair pipeline is not active.'
Assert-True ($geometryRepairSource -match 'ProtectedPoliticalFillLift = 4f' -and $geometryRepairSource -match 'TerrainRenderClearance = 2f' -and $geometryRepairSource -match 'AdjustFillToTerrainRelativeHeight\(fill\)' -and $geometryRepairSource -match 'fillGroundOffset=-2\.0' -and $geometryRepairSource -match 'ProtectedPoliticalFillLift - TerrainRenderClearance') 'The protected renderer fill lift is not reduced to the bounded terrain-relative editor height before cache replay.'
Assert-True ($geometryRepairSource -match 'TemporaryPoliticalFillColor = 0xFFD8D8D8u' -and $geometryRepairSource -match 'ApplyTemporaryLightGrayFill\(fill\)' -and $geometryRepairSource -match 'temporaryLightGrayFill=true') 'The temporary opaque light-gray political fill presentation is not applied after authored fill processing.'
Assert-True ($geometryRepairSource -match 'RemoveReverseFillFaces' -and $geometryRepairSource -match 'IsReversePair' -and $geometryDiagnosticsSource -match 'removedReverseFillTriangles=') 'Reverse fill faces are not removed or diagnosed.'
Assert-True ($geometryRepairSource -match 'PoliticalBorderCoastalFillClipper\.TryApply' -and $coastalFillClipperSource -match 'MaximumSubdivisionDepth = 4' -and $coastalFillClipperSource -match 'MinimumSignedArea = 0\.0001f' -and $coastalFillClipperSource -match 'TryFindBoundary' -and $coastalFillClipperSource -match 'TryValidateLand') 'Adaptive protected-land fill clipping is incomplete.'
Assert-True ($coastalFillClipperSource -match 'inlandGeometryPreserved=true' -and $coastalFillClipperSource -match 'islandExclusionPreserved=true' -and $coastalFillClipperSource -match 'classifier-unavailable-or-output-bound') 'Coastal fill clipping does not document its preservation and fail-safe contracts.'
Assert-True ($geometryRepairSource -match 'PoliticalBorderCoastalContourSmoother\.TryApply' -and $geometryRepairSource -match 'ribbonSegments' -and $coastalContourSource -match 'MaximumNodeDisplacement = 0\.28f' -and $coastalContourSource -match 'SmoothingPasses = 4' -and $coastalContourSource -match 'IsProtectedBoundary' -and $coastalContourSource -match 'RejectUnsafeMoves') 'The shared fill/ribbon coastal contour or its safety invariants are incomplete.'
Assert-True ($coastalContourSource -match 'BuildRibbonSegments' -and $coastalContourSource -match 'PoliticalBorderChainBuilder\.IsCoastal' -and $coastalContourSource -match 'islandExclusionPreserved=true') 'The smoothed contour is not shared with only the coastal ribbon input.'
Assert-True ($geometryRepairSource -notmatch 'PoliticalHandTracedCoastlines|handTracedOceanAndLakes' -and $project -notmatch 'PoliticalHandTracedCoastlines') 'Rejected screen-space hand-trace replacement remains in the production pipeline.'
Assert-True ($coastalContourSource -match 'ApplyNearestDisplacement' -and $coastalContourSource -match 'point \+ \(best\.Position - best\.Original\)') 'Coastal ribbon endpoints snap absolutely and can collapse the protected segment topology.'
Assert-True ($coastalContourSource -match 'MaximumRibbonCoastCorrection = CoastalSearchDistance' -and $coastalContourSource -match 'displaced, CoastalSearchDistance, MaximumRibbonCoastCorrection' -and $coastalContourSource -match 'projects completely onto that boundary' -and $coastalContourSource -match 'BoundaryIndex' -and $coastalContourSource -match 'MoveTowardNearest' -and $coastalContourSource -match 'coastCorrectedNodes=') 'Accepted coastal nodes are not fully projected onto the shared protected fill boundary within the bounded search radius.'
Assert-True ($coastalContourSource -match 'MinimumCorrectedSegmentLength = 0\.15f' -and $coastalContourSource -match 'RejectCollapsingCorrections' -and $coastalContourSource -match 'sourceLength \* 0\.5f' -and $coastalContourSource -match 'collapseRejectedNodes=') 'Coastal correction can collapse source topology and create visible ribbon cutoffs.'
Assert-True ($strokeTessellatorSource -match 'RibbonWidth = 1\.8f' -and $strokeTessellatorSource -match 'CoastalRibbonWidth = 1\.6f' -and $strokeTessellatorSource -match 'CoastalLandWidth = 1\.1f' -and $strokeTessellatorSource -match 'CoastalOuterWidth = 0\.5f' -and $strokeTessellatorSource -match 'MinimumCurveSubdivisions = 3' -and $strokeTessellatorSource -match 'MaximumCurveSubdivisions = 7' -and $strokeTessellatorSource -match 'GetSubdivisionCount' -and $strokeTessellatorSource -match 'MaximumCoastalCurveDeviation = 0\.05f') 'The adaptive rounded-ribbon or fill-aligned per-sample coastal-width contract is missing.'
Assert-True ($strokeTessellatorSource -match 'RoundedCapStepsPerHalf = 4' -and $strokeTessellatorSource -match 'EmitRoundedEndpointCaps' -and $strokeTessellatorSource -match 'AddUpwardTriangle' -and $ribbonRebuilderSource -match 'roundedEndpointCapTriangles=') 'Open ribbon-chain seams are not covered by bounded upward-only rounded caps.'
Assert-True ($strokeTessellatorSource -match 'CoastalMaskCoverWidth = CoastalOuterWidth' -and $strokeTessellatorSource -match 'coastSide == CoastSide\.Left' -and $strokeTessellatorSource -match 'CoastalLandWidth \* _borderWidthScale' -and $strokeTessellatorSource -match 'CoastalOuterWidth \* _borderWidthScale' -and $ribbonRebuilderSource -match 'coastalLandWidth=' -and $ribbonRebuilderSource -match 'coastalOuterWidth=') 'The coastal ribbon is not thinned only from its classified water-facing outer side.'
Assert-True ($authoredOverridesSource -match 'ConfigureWidthScale' -and $strokeTessellatorSource -match 'EffectiveRibbonWidth' -and $ribbonRebuilderSource -match 'widthScale=' -and $ribbonRebuilderSource -match 'effectiveWidth=') 'The persisted global width scale is not applied and diagnosed across all border ribbons.'
Assert-True ($geometryCacheSource -match 'enum BorderLineStyle : byte \{ Solid, Dashed, Double \}' -and $authoredOverridesSource -match 'ParseStyle' -and $chainBuilderSource -match 'segments\[candidate\]\.Style != style' -and $strokeTessellatorSource -match 'DashCycleSections = 5' -and $strokeTessellatorSource -match 'DoubleLineInnerRatio = 0\.45f') 'Solid, dashed, and double authored border geometry contracts are incomplete.'
Assert-True ($strokeTessellatorSource -match 'firstRadius = startWidth' -and $strokeTessellatorSource -match 'secondRadius = startWidth' -and $strokeTessellatorSource -notmatch 'capRadius = Math\.Max') 'Rounded endpoint caps ignore asymmetric coast widths and can bulge back over water.'
Assert-True ($strokeTessellatorSource -match 'PrepareCoastalLandHeights' -and $strokeTessellatorSource -match 'coastSide == CoastSide\.Both' -and $strokeTessellatorSource -match 'CoastalHalfPoliticalWidth \* 1\.5f, CoastalRibbonWidth' -and $strokeTessellatorSource -match 'candidateHeight > height' -and $strokeTessellatorSource -match 'sample\.CoastalLandHeight\s*\+\s*FrontierHeight' -and $strokeTessellatorSource -match 'height < coastalLandLevel' -and $ribbonRebuilderSource -match 'coastalLandHeightExpandedSearchSamples=') 'Coastal chains are not clamped to their highest resilient validated adjacent-land heights with auditable lift diagnostics.'
Assert-True ($strokeTessellatorSource -match 'CoastalVisibilityClearance = 0f' -and $strokeTessellatorSource -match 'FrontierHeight \+ CoastalVisibilityClearance' -and $ribbonRebuilderSource -match 'coastalVisibilityClearance=') 'Validated coastal ribbons retain an added Z clearance that can detach them from the terrain.'
Assert-True ($strokeTessellatorSource -match 'FillCoastalLandHeightGaps' -and $strokeTessellatorSource -match 'MaximumCoastalHeightGapSamples = 12' -and $strokeTessellatorSource -match 'MaximumCoastalHeightGapDistance = 4f' -and $ribbonRebuilderSource -match 'coastalLandHeightInterpolatedSamples=' -and $ribbonRebuilderSource -match 'coastalLandHeightUnresolvedSamples=') 'Short rejected coastal-height runs are not bridged between nearby validated samples with bounded diagnostics.'
Assert-True ($strokeTessellatorSource -match 'HasCoastalSamples' -and $strokeTessellatorSource -match 'samples\[samples\.Count - 1\]\.Coastal = true' -and $strokeTessellatorSource -match 'if \(!sample\.Coastal\) continue' -and $ribbonRebuilderSource -match 'coastalSamples=') 'Mixed frontier chains do not retain per-cross-section coastal width and height classification.'
Assert-True ($strokeTessellatorSource -match 'if \(coastal\) result\.EmittedCoastalSections\+\+' -and $strokeTessellatorSource -notmatch 'SkippedCoastalSections|if \(coastal\)[\s\S]{0,80}continue' -and $ribbonRebuilderSource -match 'emittedCoastalSections=') 'Ocean/lake frontier sections are still suppressed instead of emitted.'
Assert-True ($strokeTessellatorSource -notmatch 'if \(!samples\[0\]\.Coastal\)|if \(!samples\[lastSample\]\.Coastal\)' -and $strokeTessellatorSource -match 'EmitRoundedEndpointCap\(') 'Open coastal chains can still terminate without endpoint caps.'
Assert-True ($strokeTessellatorSource -match 'AddUpwardQuad' -and $strokeTessellatorSource -notmatch 'DoubleSided|RoundCap|TriangleFan|AddHalfRoundCap') 'The rebuilt ribbon still creates coplanar backfaces or internal triangle-fan caps.'
Assert-True ($chainBuilderSource -match 'directed chains' -and $chainBuilderSource -match 'Incidents\.Count != 2' -and $chainBuilderSource -match 'IsCoastal') 'Frontier topology is not decomposed into stable coastal chains.'
Assert-True ($ribbonRebuilderSource -match 'PoliticalBorderChainBuilder\.Build' -and $ribbonRebuilderSource -match 'Shared-chain political ribbon rebuilt' -and $ribbonRebuilderSource -match 'validatedCenterlinesAuthoritative=true') 'The shared-chain ribbon orchestrator contract is incomplete.'
Assert-True ($ribbonRebuilderSource -match 'chainGeometry\.Triangles\.Count == 0' -and $ribbonRebuilderSource -match 'emptyChains\+\+' -and $geometryDiagnosticsSource -match 'ribbonEmptyChains=') 'Fully excluded empty chains incorrectly abort the complete ribbon rebuild.'
Assert-True ($strokeTessellatorSource -match 'ClassifyChainLandSide' -and $strokeTessellatorSource -match 'TryClassifyFrontierLand') 'Read-only coastal-side diagnostics are incomplete.'
Assert-True ($strokeTessellatorSource -notmatch 'ConstrainLandWidth|IsLandwardSection|IsLandwardSpan|requireLeftLand|requireRightLand') 'Accepted coastal source topology is still overridden by a fallible land-half width constraint.'
Assert-True ($strokeTessellatorSource -match 'ComputeSharedNormals' -and $strokeTessellatorSource -match 'SharedCrossSections' -and $strokeTessellatorSource -match 'IsUpwardQuad' -and $strokeTessellatorSource -match 'MinimumSignedTriangleArea') 'Shared joins or positive-winding output invariants are incomplete.'
Assert-True ($strokeTessellatorSource -match 'SignedArea\(first, second, fourth\)' -and $strokeTessellatorSource -match 'SignedArea\(second, third, fourth\)' -and $strokeTessellatorSource -match 'AlternativeDiagonalSections' -and $ribbonRebuilderSource -match 'alternativeDiagonalSections=') 'Concave ribbon quads do not select their valid alternate diagonal or diagnose its use.'
Assert-True ($strokeTessellatorSource -match 'FindMaximumSafeScale' -and $strokeTessellatorSource -match 'ApplyWidthCaps' -and $strokeTessellatorSource -match 'WidthStabilizationPasses = 3' -and $strokeTessellatorSource -notmatch '\*= 0\.5f') 'Ribbon safety still uses order-dependent width collapse instead of simultaneous bounded constraints.'
Assert-True ($strokeTessellatorSource -match 'StabilizeWidths\(samples, result\)' -and $strokeTessellatorSource -match 'leftWindingSafe' -and $strokeTessellatorSource -match 'rightWindingSafe' -and $strokeTessellatorSource -match 'MinimumSignedTriangleArea = 0\.0001f') 'Accepted ribbon halves are not constrained solely by positive-winding safety or can emit diagnostic slivers.'
Assert-True ($strokeTessellatorSource -match 'Drape' -and $strokeTessellatorSource -match 'TrySamplePreparedHeight' -and $strokeTessellatorSource -match 'FrontierHeight = 5f') 'Generated ribbon vertices are not independently terrain draped.'
Assert-True ($authoredOverridesSource -match 'SampleTerrain\(first, nearest, out firstPrepared\)' -and $authoredOverridesSource -match 'BorderOptimizerRuntime.TrySamplePreparedHeight\(point, out height\)' -and $authoredOverridesSource -match 'localTerrainFallbacks=') 'Authored border endpoints are not sampled from the local prepared terrain with aggregate fallback diagnostics.'
Assert-True ($strokeTessellatorSource -match 'sample.FallbackHeight \+ FrontierHeight') 'Prepared-height misses do not preserve the normal terrain-relative border elevation.'
Assert-True ($source -notmatch 'GetWaterLevelAtPosition|WaterLevelCache|TryGetWaterLevel' -and $strokeTessellatorSource -notmatch 'CoastalWaterClearance|CoastalWaterLiftedVertices') 'The disproven per-vertex water-height workaround remains in the release path.'
Assert-True ($ribbonRebuilderSource -match 'rebuiltSegments != segments\.Count' -and $geometryRepairSource -match 'ribbonRebuilt=') 'Ribbon reconstruction does not fail safely or diagnose its result.'
Assert-True ($geometryDiagnosticsSource -match 'ribbonSourceTriangles=' -and $geometryDiagnosticsSource -match 'ribbonGeneratedTriangles=' -and $geometryDiagnosticsSource -match 'ribbonRemovedCapTriangles=' -and $geometryDiagnosticsSource -match 'ribbonRemovedBackfaceTriangles=' -and $geometryDiagnosticsSource -match 'ribbonCurvedCoastalSegments=' -and $geometryDiagnosticsSource -match 'ribbonCurveSubdivisions=' -and $geometryDiagnosticsSource -match 'ribbonWidth=') 'Rounded coastal-ribbon diagnostics are incomplete.'
Assert-True ($geometryCacheSource -match 'cache was rejected; a cold rebuild will be used' -and $geometryCacheSource -match 'cache could not be written; rendered geometry remains active') 'Persistent-cache failure paths are not fail-open.'
Assert-True ($geometryCacheSource -notmatch 'Task\.Run|new Thread|ThreadPool') 'Persistent geometry capture or replay moves native mesh work off the main thread.'
Assert-True ($publishedLayoutSource -match 'AuthoredBorders' -and $publishedLayoutSource -match 'layoutCount == 1' -and $eagerWarmupSource -match 'PublishedBorderLayoutPresence\.IsPresent\(\)' -and $eagerWarmupSource -match 'persistent generated-geometry replay is bypassed') 'Published Core layouts can be overwritten by generated cache replay.'
Assert-True ($source -match 'AfterExactHeight' -and $source -match 'AfterNativeTerrain' -and $source -match 'TryGetPublishedExactHeight' -and $source -match 'TryGetPublishedNativeTerrain' -and $source -match 'RecordPublishedExactHeight' -and $source -match 'RecordPublishedNativeTerrain' -and $source -match 'ShouldUsePreparedProbe\(\s*BorderOptimizerRuntime\.IsPublishedLayoutActive, exactMemoHit\)' -and $source -match 'ShouldUsePreparedProbe\(\s*BorderOptimizerRuntime\.IsPublishedLayoutActive, exactMemoHit\)') 'Published layouts do not preserve exact native terrain probe results or can use interpolation after an exact-cache miss.'
Assert-True ($publishedProbeMemoSource -match 'FieldOffset\(0\)' -and $publishedProbeMemoSource -match 'Dictionary<PointKey, ProbeResult>' -and $publishedProbeMemoSource -match 'success = result.Success' -and $publishedProbeMemoSource -match 'MaximumEntries = 262144' -and $publishedProbeMemoSource -match 'return false;' -and $publishedProbeMemoSource -match 'void Clear\(\)') 'Published exact-probe memoization can approximate coordinates, lose invalid out values, outlive a scene, or grow without a native fallthrough bound.'
Assert-True ($source -match '_publishedLayoutActive = PublishedBorderLayoutPresence\.IsPresent\(\)' -and $source -match 'prepared-grid interpolation is disabled' -and $source -match 'if \(_publishedLayoutActive\) return true;' -and $source -match 'PublishedExactHeights\.Clear\(\)' -and $source -match 'PublishedNativeTerrain\.Clear\(\)' -and $project -match 'PoliticalBorderPublishedExactProbeMemoization\.cs') 'Published exact-probe memoization is not scoped to the active scene, bypasses native builder readiness, or still prepares an unused approximate snapshot.'
Assert-True ($eagerWarmupSource -match 'EnsurePublishedLayoutReady\(\)' -and $eagerWarmupSource -match 'Aoc\.BorderEditPrototype\.PrototypeRuntime' -and $eagerWarmupSource -match 'PublishedReady' -and $eagerWarmupSource -match 'published-layout readiness was verified by its sidecar') 'Eager warmup can claim published-layout readiness before the published sidecar succeeds.'
Assert-True ($source -match 'HandleIfBlockerStatesDisabled' -and $source -match 'C7360E71DA06799A0CB6C00C4A0CFAB5877621197BA25101433AC28654D169E2' -and $eagerWarmupSource -match 'BeforeMapSceneVisible' -and $eagerWarmupSource -match 'LoadingWindow\.IsLoadingWindowActive' -and $eagerWarmupSource -match 'SetPublishedLoadingScope\(true\)' -and $eagerWarmupSource -match 'SetPublishedLoadingScope\(false\)') 'Published layouts are not gated to the hash-pinned MapScreen readiness callback with an explicit sidecar loading scope.'
Assert-True ($documentation -match 'scene-scoped exact-probe memo' -and $documentation -match 'exact floating-point XY pair' -and $documentation -match 'including failed terrain probes' -and $documentation -match 'capped at 262,144 entries' -and $documentation -match 'bounded to 30 seconds' -and $documentation -match 'separate pre-map-frame') 'Published-layout exact-probe memoization or sequential startup budgets are undocumented.'
Assert-True ($geometryDiagnosticsSource -match 'degenerateTriangles=' -and $geometryDiagnosticsSource -match 'oversizedTriangles=' -and $geometryDiagnosticsSource -match 'sourceTiltedFillTriangles=' -and $geometryDiagnosticsSource -match 'replayFlatNormals=true') 'Triangle artifact diagnostics are incomplete.'
Assert-True ($artifactDiagnosticsSource -match 'MaximumLocationSamples = 12' -and $artifactDiagnosticsSource -match 'Political coastal artifact samples:' -and $artifactDiagnosticsSource -match 'AnalyzeNearCoastTriangles') 'Coastal artifact location diagnostics are missing or unbounded.'
Assert-True ($geometryDiagnosticsSource -match 'sourceNearCoastTiltedFillTriangles=' -and $geometryDiagnosticsSource -match 'sourceNearCoastHighReliefFillTriangles=' -and $geometryDiagnosticsSource -match 'sourceNearCoastNonUpwardFrontierTriangles=' -and $geometryDiagnosticsSource -match 'sourceFrontierReversePairs=' -and $geometryDiagnosticsSource -match 'outputNearCoastNonUpwardTriangles=' -and $geometryDiagnosticsSource -match 'outputFrontierReversePairs=') 'Separate coastal fill and ribbon diagnostics are incomplete.'
Assert-True ($geometryDiagnosticsSource -match 'coastalLandLeftSegments=' -and $geometryDiagnosticsSource -match 'coastalLandRightSegments=' -and $geometryDiagnosticsSource -match 'coastalAmbiguousSegments=' -and $geometryDiagnosticsSource -match 'ribbonUnsafeCurveFallbackSegments=' -and $geometryDiagnosticsSource -match 'ribbonPreparedHeightFallbackVertices=') 'Landward-safe coastal output diagnostics are incomplete.'
Assert-True ($geometryDiagnosticsSource -match 'ribbonChains=' -and $geometryDiagnosticsSource -match 'ribbonSharedCrossSections=' -and $geometryDiagnosticsSource -match 'ribbonWidthConstrainedSamples=' -and $geometryDiagnosticsSource -match 'ribbonSuppressedUnsafeSections=' -and $geometryDiagnosticsSource -match 'ribbonUnsafeCoastalSamples=') 'Shared-chain safety diagnostics are incomplete.'
Assert-True ($ribbonDiagnosticSource -match 'MaximumSamplesPerCategory = 24' -and $ribbonDiagnosticSource -match 'Political ribbon constraint samples:' -and $ribbonDiagnosticSource -match 'Political ribbon suppression samples:' -and $ribbonDiagnosticSource -match 'normalDot=' -and $ribbonDiagnosticSource -match 'reason=') 'Bounded location diagnostics for slim or suppressed ribbon sections are incomplete.'
Assert-True ($geometryDiagnosticsSource -match 'coastalFillClipSourceTriangles=' -and $geometryDiagnosticsSource -match 'coastalFillClipGeneratedTriangles=' -and $geometryDiagnosticsSource -match 'coastalFillClipBoundaryVertices=' -and $geometryDiagnosticsSource -match 'coastalFillClipMaximumDepth=') 'Adaptive coastal-fill diagnostics are incomplete.'
Assert-True ($geometryDiagnosticsSource -match 'coastalContourBoundaryEdges=' -and $geometryDiagnosticsSource -match 'coastalContourMovedNodes=' -and $geometryDiagnosticsSource -match 'coastalContourRejectedNodes=' -and $geometryDiagnosticsSource -match 'coastalContourMaximumDisplacement=') 'Shared coastal-contour diagnostics are incomplete.'
Assert-True ($geometryCacheSource -match 'UpdateOutputCounts' -and $geometryDiagnosticsSource -match 'frontierTriangles=') 'Final repaired output counts are not diagnosed.'
Assert-True ($geometryDiagnosticsSource -match 'frontierEndpoints=' -and $geometryDiagnosticsSource -match 'frontierJunctions=' -and $geometryDiagnosticsSource -match 'sharpFrontierTurns=' -and $geometryDiagnosticsSource -match 'maximumSmoothingDisplacement=') 'Frontier anomaly diagnostics are incomplete.'
Assert-True ($geometryDiagnosticsSource -match 'smoothingPasses=' -and $geometryDiagnosticsSource -match 'finalSharpFrontierTurns=' -and $geometryDiagnosticsSource -match 'fillAdjustedVertices=' -and $geometryDiagnosticsSource -match 'frontierAdjustedVertices=') 'Post-transform smoothing diagnostics are incomplete.'
Assert-True ($geometryDiagnosticsSource -match 'MaximumDiagnosticTriangles' -and $geometryDiagnosticsSource -match 'Cached geometry diagnostics are invalid') 'Cached diagnostic metadata is not bounded or validated.'
Assert-True ($project -match '<AssemblyName>AgesOfCalradia\.PoliticalBorderOptimizer</AssemblyName>' -and $project -match 'PublishedBorderLayoutPresence\.cs' -and $project -match 'TaleWorlds\.CampaignSystem' -and $project -match 'TaleWorlds\.ObjectSystem' -and $project -match 'TaleWorlds\.Engine' -and $project -match 'TaleWorlds\.DotNet' -and $project -notmatch 'PoliticalFactionColorOverrides\.cs|PoliticalHandTracedCoastlines' -and $project -match 'PoliticalBorderEagerWarmup\.cs' -and $project -match 'PoliticalBorderGeometryCache\.cs' -and $project -match 'PoliticalBorderGeometryDiagnostics\.cs' -and $project -match 'PoliticalBorderArtifactDiagnostics\.cs' -and $project -match 'PoliticalBorderGeometryRepair\.cs' -and $project -match 'PoliticalBorderCoastalFillClipper\.cs' -and $project -match 'PoliticalBorderCoastalContourSmoother\.cs' -and $project -match 'PoliticalBorderChainBuilder\.cs' -and $project -match 'PoliticalBorderStrokeTessellator\.cs' -and $project -match 'PoliticalBorderRibbonDiagnosticSamples\.cs' -and $project -match 'PoliticalBorderRibbonRebuilder\.cs') 'The sidecar project contract is incomplete.'
Assert-True ($project -notmatch 'PoliticalBorderVoronoiClipper\.cs|PoliticalBorderExactFrontier\.cs|PoliticalBorderGeometrySmoothing\.cs') 'A rejected shape-changing geometry transform remains in the compiled optimizer.'
Assert-True ($manifest -match 'AgesOfCalradia\.PoliticalBorderOptimizer\.dll' -and $manifest -match 'PoliticalBorderOptimizerSubModule') 'The optimizer is not registered as a separate submodule assembly.'
Assert-True ($documentation -match 'Harmony targets and compatibility' -and $documentation -match 'Failure behavior') 'Harmony target compatibility documentation is incomplete.'

if (Test-Path -LiteralPath $AssemblyPath -PathType Leaf) {
    $ildasm = 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools\x64\ildasm.exe'
    if (Test-Path -LiteralPath $ildasm) {
        $assemblyText = & $ildasm $AssemblyPath /text
        Assert-True (@($assemblyText | Select-String 'PoliticalBorderOptimizerSubModule').Count -gt 0) 'Compiled sidecar entry point is missing.'
        Assert-True (@($assemblyText | Select-String 'CampaignMapTerrainGridCache').Count -gt 0) 'Compiled sidecar target names are missing.'
    }
}

if (Test-Path -LiteralPath $ApprovedRendererPath -PathType Leaf) {
    $approvedHash = '560F1B5181F8CC2EFE51564D8675FD3089E722606FA55B0B166D36ECD9868D8E'
    $actualHash = (Get-FileHash -LiteralPath $ApprovedRendererPath -Algorithm SHA256).Hash
    Assert-True ([string]::Equals($actualHash, $approvedHash, [StringComparison]::OrdinalIgnoreCase)) 'Runtime target audit received a renderer other than the approved protected assembly.'
    $ildasm = 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools\x64\ildasm.exe'
    if (Test-Path -LiteralPath $ildasm) {
        $rendererText = & $ildasm $ApprovedRendererPath /text
        foreach ($target in @(
            'CampaignMapTerrainGridCache::BeginOrAdvance',
            'CampaignMapTerrainGridCache::Reset',
            'CampaignMapTerrainGridCache::Clear',
            'CampaignMapTerrainGridCache::TrySampleHeight',
            'CampaignMapTerrainGridCache::TrySampleExactHeight',
            'CampaignMapTerrainGridCache::TryGetNativeTerrain',
            'CampaignMapTerrainGridCache::IsPoliticalLandExact',
            'CampaignKingdomBorderBehavior::OnGameLoadFinished',
            'CampaignKingdomBorderBehavior::OnSessionLaunched',
            'CampaignKingdomBorderBehavior::TryGetCampaignMapScene',
            'CampaignKingdomBorderBehavior::RebuildBorders',
            'CampaignKingdomBorderBehavior::PrepareTerritoryCells',
            'CampaignKingdomBorderBehavior::BuildOwnershipSignature',
            'CampaignKingdomBorderBehavior::BuildSites',
            'CampaignKingdomBorderBehavior::ReplacePoliticalFillEntities',
            'CampaignKingdomBorderBehavior::ReplacePoliticalFrontierEntities',
            'CampaignPoliticalTerritoryFill/Builder::Advance',
            'CampaignPoliticalTerritoryFill/Builder::AddRowEntity',
            'CampaignPoliticalTerritoryFill/Builder::AddFrontierEntity',
            'CampaignPoliticalTerritoryFill/Builder::AddFrontierSegment',
            'CampaignPoliticalTerritoryFill/Builder::Cancel',
            'CampaignPoliticalTerritoryFill/Builder::TryGetFrontierPoint',
            'CampaignPoliticalTerritoryFill/Builder::get_IsComplete')) {
            Assert-True (@($rendererText | Select-String -SimpleMatch $target).Count -gt 0) "Approved renderer target is missing: $target"
        }
        foreach ($field in @('_minX', '_minY', '_maxX', '_maxY')) {
            Assert-True (@($rendererText | Select-String -SimpleMatch "CampaignMapTerrainGridCache::$field").Count -gt 0) "Approved renderer field is missing: $field"
        }
        foreach ($field in @('_mapScene', '_politicalOverlayView', '_dirty', '_loggedFirstBuild', '_pendingTerritoryCells', '_pendingFillBuilder', '_lastOwnershipSignature', '_pendingMinX', '_pendingMinY', '_pendingMaxX', '_pendingMaxY')) {
            Assert-True (@($rendererText | Select-String -SimpleMatch "CampaignKingdomBorderBehavior::$field").Count -gt 0) "Approved renderer eager-warmup field is missing: $field"
        }
    }
}

if (Test-Path -LiteralPath $MapScreenAssemblyPath -PathType Leaf) {
    $mapScreenHash = 'C7360E71DA06799A0CB6C00C4A0CFAB5877621197BA25101433AC28654D169E2'
    Assert-True ([string]::Equals((Get-FileHash -LiteralPath $MapScreenAssemblyPath -Algorithm SHA256).Hash, $mapScreenHash, [StringComparison]::OrdinalIgnoreCase)) 'MapScreen readiness target is not the reviewed SandBox.View assembly.'
    $ildasm = 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools\x64\ildasm.exe'
    if (Test-Path -LiteralPath $ildasm) {
        $mapScreenText = & $ildasm $MapScreenAssemblyPath /text
        foreach ($target in @('MapScreen::HandleIfBlockerStatesDisabled', 'MapScreen::get_MapScene', 'MapScreen::get_SceneLayer', 'MapScreen::_isSceneViewEnabled', 'View::SetEnable(bool)', 'SceneView::ReadyToRender', 'SceneView::CheckSceneReadyToRender')) {
            Assert-True (@($mapScreenText | Select-String -SimpleMatch $target).Count -gt 0) "Reviewed MapScreen readiness member is missing: $target"
        }
    }
}

& dotnet run --project (Join-Path $Root 'Tests\PoliticalBorderOptimizer\PublishedLayoutExactProbeMemoizationTests.csproj') -c Release
if($LASTEXITCODE -ne 0){throw 'Published probe/loading dismissal behavioral verification failed.'}
Write-Host 'Political border optimizer verification passed: approved-hash gating, fail-open terrain caching, aggregate diagnostics, loading dismissal, and separate sidecar registration are present.'
